---
title: "DRF_summary"
author: "_______"
date: "_______"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, message=FALSE}
library(ggplot2)
library(dplyr)
library(rtracklayer)
library(DT)
library(plotly)
library(ggsignif)
library(tidyverse)
```

```{r Pointing script to data, setting environment variables}
short_read_raw <- 'COLO829_SR_dark_regions.bed' #Dark region bed file generated using simpler_DRF.py
long_read_raw <- 'COLO829_LR_dark_regions.bed' #Dark region bed file generated using simpler_DRF.py
ref_genome <- 'hg38' #Setting reference genome for dark region coverage calculations 
chroms <- c('chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 
            'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY')
```

```{r Loading DRs, echo=FALSE}
sr.dr <- read.csv(file = short_read_raw, sep = '\t', header = FALSE)
lr.dr <- read.csv(file = long_read_raw, sep = '\t', header = FALSE)
```

```{r Reformatting/Cleaning Data, echo=FALSE}
names(sr.dr)[c(1, 2, 3, 4)] <- c('chromosome', 'start', 'end', 'dark_reason') #Giving the columns names
names(lr.dr)[c(1, 2, 3, 4)] <- c('chromosome', 'start', 'end', 'dark_reason') #Giving the columns names

sr.dr$chromosome <- factor(sr.dr$chromosome, levels = chroms) #Making chromosome a factor 
lr.dr$chromosome <- factor(lr.dr$chromosome, levels = chroms) #Making chromosome a factor

sr.dr <- subset(sr.dr, sr.dr$chromosome != "NA") #Dropping NA's
lr.dr <- subset(lr.dr, lr.dr$chromosome != "NA") #Dropping NA's

sr.dr$width <- (sr.dr$end - sr.dr$start) + 1 #Adding column with dark region widths
lr.dr$width <- (lr.dr$end - lr.dr$start) + 1 #Adding column with dark region widths

#Reorganizing the short read dark reason factors for later analysis
sr.dr$dark_reason <- factor(x = sr.dr$dark_reason,
                                      levels = c("{'depth', 'mapq', 'phred'}", "{'depth', 'phred', 'mapq'}", "{'mapq', 'depth', 'phred'}", "{'phred', 'depth', 'mapq'}", "{'phred', 'mapq', 'depth'}", "{'mapq', 'phred', 'depth'}", "{'depth', 'mapq'}", "{'mapq', 'depth'}", "{'depth', 'phred'}", "{'phred', 'depth'}", "{'mapq', 'phred'}", "{'phred', 'mapq'}", "{'depth'}", "{'mapq'}", "{'phred'}"),
                                      labels = c("{'depth', 'mapq', 'phred'}", "{'depth', 'mapq', 'phred'}", "{'depth', 'mapq', 'phred'}", "{'depth', 'mapq', 'phred'}", "{'depth', 'mapq', 'phred'}", "{'depth', 'mapq', 'phred'}", "{'depth', 'mapq'}", "{'depth', 'mapq'}", "{'depth', 'phred'}", "{'depth', 'phred'}", "{'mapq', 'phred'}", "{'mapq', 'phred'}", "{'depth'}", "{'mapq'}", "{'phred'}"))

sr.dr$dark_reason <- droplevels(sr.dr$dark_reason) #Dropping unused short read dark reason factor levels

#Doing the same as above for the long read dark reasons
lr.dr$dark_reason <- factor(x = lr.dr$dark_reason, 
                            levels = c("{'depth', 'phred'}", "{'depth'}", "{'phred', 'depth'}", "{'phred'}"),
                            labels = c("{'depth', 'phred'}", "{'depth'}", "{'depth', 'phred'}", "{'phred'}"))

lr.dr$dark_reason <- droplevels(lr.dr$dark_reason)

sr.dr$method <- 'Short Read'
lr.dr$method <- 'Long Read'

dark.regions <- rbind(sr.dr, lr.dr)

rm(long_read_raw, short_read_raw) #Cleaning things up
```

```{r Summary Statistics, echo=FALSE}
#Getting summary statistics for both groups

stats <- dark.regions %>% group_by(method, chromosome) %>% dplyr::summarize(mean = mean(width), sd = sd(width), max = max(width), total = sum(width))

```

```{r Converting dark region dataframe into GRanges objects, echo=FALSE}

sr.gr <- makeGRangesFromDataFrame(sr.dr, 
                                  keep.extra.columns = TRUE,
                                  seqnames.field = 'chromosome',
                                  start.field = 'start',
                                  end.field = 'end')

lr.gr <- makeGRangesFromDataFrame(lr.dr, 
                                  keep.extra.columns = TRUE,
                                  seqnames.field = 'chromosome',
                                  start.field = 'start',
                                  end.field = 'end')

```

```{r Getting total coverage, message=FALSE, echo=FALSE}

reference_genome <- GRangesForBSGenome(genome = ref_genome, chrom = chroms, ranges = NULL) #Loading reference genome

ref_genome_df <- data.frame(reference_genome) #Converting the reference genome to a dataframe to use for the next two lines to get coverage

stats$percent_dark = stats$total / ref_genome_df$width * 100

genome_length <- sum(width(reference_genome)) #Getting total width of reference genome chromosomes

sr.dr.length <- sum(width(sr.gr)) #Getting total width of all dark regions 
lr.dr.length <- sum(width(lr.gr)) #Getting total width of all dark regions 
```

Dark region coverage of short-read data: `r sr.dr.length / genome_length * 100`   
Dark region coverage of long-read data: `r lr.dr.length / genome_length * 100`

```{r Interactive Tables}

DT::datatable(stats) #Interactive data table with stats

```


```{r Plotting widths}

#Running t-tests between means of widths
p.values <- dark.regions %>%
  group_by(chromosome) %>%
  summarise(p=wilcox.test(width~method, exact=FALSE, paired=FALSE)$p.value,
            y=log10(max(width))) %>%
  mutate(labels = case_when(p >= 0.05 ~ "n.s.",
                            p >= 0.01 ~ "*",
                            p >= 0.001 ~ "**",
                            p < 0.001 ~ "***"))

#Plotting widths
dark.regions %>%
  ggplot(aes(x=chromosome, y=width, fill=method)) +
  geom_boxplot() +
  geom_signif(y_position = 8, 
              xmin = p.values$chromosome,
              xmax = p.values$chromosome, 
              annotations = p.values$labels) + 
  labs(x = 'Chromosome', y = 'Dark Region Width (bp)', fill = 'Method') +
  scale_y_continuous(trans='log10') +
  scale_x_discrete(limits=chroms) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        axis.title.x = element_text(vjust = -2.0))

```

```{r Plotting coverage by chromosome, echo=FALSE}

p2 <- ggplot(stats, aes(x=chromosome, y=percent_dark)) +
  geom_bar(aes(fill = method), position = "dodge", stat="identity") +
  scale_x_discrete(limits=chroms) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))

ggplotly(p2)
```

Importantly it looks like the reference genome used here differs somewhat from the reference genome used in the simpler_DRF program, so actual coverage differs, look at the 'summary_stats' txt file to find coverage 

```{r Dark Reason Stats}

reason_sum <- group_by(dark.regions, method, chromosome, dark_reason) %>% dplyr::summarise(count=n())
 
#reason_sum$percent_total <- reason_sum$count / reason_sum$total_annots * 100
  
p3 <- ggplot(reason_sum, aes(fill = dark_reason, y = count, x = chromosome)) +
            geom_bar( position="fill", stat = "identity") + 
            facet_grid(~ method) +
            labs(x = '', y = 'Percent Total', fill = 'Dark Reason') +
            theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
                  axis.title.x = element_text(vjust = -10),
                  axis.title.y = element_text(hjust = -10))

ggplotly(p3)

```

























