#PBS -N pile_LR_COLO829
#PBS -r n
#PBS -l ncpus=1,mem=10GB,walltime=47:15:00
#PBS -m ae
#PBS -M k.henry@dkfz-heidelberg.de

module load samtools/1.9

cd /working/lab_nicw/kevinH/projects/dark_regions/

samtools mpileup -f /reference/genomes/GRCh38_no_alt_analysis_set/indexes/BWAKIT_0.7.12/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa -s -O --output-QNAME -A -B -Q 1 -R -x -o COLO829_LR.pileup -O -aa /working/lab_nicw/marjanM/LongRead/colo829/bam/cated_pass_test_ngmlr.bam

#Long-read pileup generator, grabbed from here:
#/working/lab_nicw/liamM/nano/COLO829/pile

